on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - run: composer install --ansi --no-progress --prefer-dist --no-interaction
      - run: php shop-example-wasm/build.php
      - uses: actions/upload-artifact@v4
        with:
          name: shop-example-wasm-build
          path: shop-example-wasm/.build

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: git@github.com:uuf6429/uuf6429.github.io.git
          ref: main
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: shop-example-wasm-build
      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          ls -lah
      #- run: git push origin master
